fix(require-index): stop suggest fix for missing index.js files
ExodusMovement/eslint-plugin-require-extensions pull request #4
Opened 2024-08-21 17:24 UTC by marcoskichel

## Description
Currently the `require-index` rule will suggest a fix that includes a reference to a `index.js` that might be missing, this PR changes the rule to only suggest the fix in case that file actually exists, otherwise the user still receives a warning but the is not able to auto fix it.

2024-08-21 18:21 UTC, mvayngrib approved these changes

2024-08-22 07:33 UTC, ChALkeR approved these changes

2024-08-22 07:41 UTC, ChALkeR requested changes
Looking at this closer, it should also opt-out from autofixing to dir not just if `${path}${fileExt}` exists, but if any of `${path}${fileExt}`, `${path}.js`, `${path}.json`, `${path}.node` exist, even if `${path}/index.js` exists

2024-08-22 07:44 UTC, ChALkeR commented on index.js
>              const conflictingFile = join(dirname(path), `${basename(path)}${fileExt}`);
unsure if this is different from just `${path}${fileExt}`

2024-08-22 08:02 UTC, ChALkeR commented on index.js
> +                const indexFile = join(path, 'index.js');
Otherwise this will break typescript, which should check the existance of `dir/index.ts` _and_ `dir/index.js` and autofix to... likely `dir/index.js` for now

2024-08-22 17:06 UTC, ChALkeR commented
https://github.com/ExodusMovement/eslint-plugin-require-extensions/pull/3#discussion_r1726564731 should be captured, too

2024-08-22 19:51 UTC, marcoskichel commented on index.js
> +                const indexFile = join(path, 'index.js');
Should def check if ts exists and return the correct version of it in the fix, but we probably don't need to care about `fileExt` since we are checking if the path is a directory in the line above.

2024-08-23 11:24 UTC, ChALkeR commented on index.js
> +                const indexFile = join(path, 'index.js');
> but we probably don't need to care about fileExt
Usure

I took a closer loook

Context:
1. The input code might be not .ts/.js but something else
2. https://nodejs.org/api/modules.html#all-together
3. https://nodejs.org/api/modules.html#folders-as-modules
4. https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution
5. under tsc, we can be importing `./dir/index.ts` as `./dir` from a `.js` file

So, combining with the resolution mechanism, for `./foo`, typescript should try to load (not necessary in this order, there are differences in details) :
* `./foo.ts`
* `./foo.tsx`
* `./foo.d.ts`
* `./foo.js`
* `./foo.jsx`
* `./foo.json`
* `./foo.node`
* `./foo/package.json`
* `./foo/index.tsx`
* `./foo/index.d.ts`
* `./foo/index.js`
* `./foo/index.jsx`

Trace for `tsc` shows (might be lacking runtime resolution):
```
2024-08-23 13:34:27.823286 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo.ts                                                       2024-08-23 13:34:27.823335 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo.tsx                                                      2024-08-23 13:34:27.823342 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo.d.ts                                                     2024-08-23 13:34:27.823346 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo                                                          2024-08-23 13:34:27.823406 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo/package.json                                             2024-08-23 13:34:27.823461 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo/index.ts                                                 2024-08-23 13:34:27.823465 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo/index.tsx                                                2024-08-23 13:34:27.823471 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo/index.d.ts                                               2024-08-23 13:34:27.823511 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo.js                                                       2024-08-23 13:34:27.823516 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo.jsx                                                      2024-08-23 13:34:27.823533 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo/index.js                                                 2024-08-23 13:34:27.823580 +04          0.0(0.0)         VFS_LOOKUP                           /_test/foo/index.jsx 
```

That said, `/index.{whatever-ts}` should be fine if we are coming from typescript resolution and none of parent `.ts`/`.tsx`/`.d.ts`/`.js.`/`.jsx`/`.node`/`.json` exist

Given that we might come from something else than tsx, let's do the following for the directory index replacement
1) if `dir.ts`, `dir.tsx`, `dir.d.ts`, `dir.js`, `dir.jsx`, `dir.node`, `dir.json`, `dir.fileExt`, or `dir/package.json` exist -- bail out
2) if `dir/index.js`, `dir/index.ts` and `dir/index.fileExt` do not exist -- bail out
3) if `dir/index.js`, `dir/index.ts` do not exist and fileExt is not `.tsx` or `.jsx` -- bail out
4) replace `dir` import with `dir/index.js`

2024-08-23 11:26 UTC, ChALkeR commented on index.js
> +                const indexFile = join(path, 'index.js');
(sorry for complication, non-esm path import resolution is just... a bit tricky, and we need to be sure we don't cause accidental regressions with autofixes)

2024-08-24 21:12 UTC, marcoskichel commented on index.js
> +                const indexFile = join(path, 'index.js');
Indeed, tricky it is 🤣 , thanks for the help though, I will implement the logic you suggested above

2024-08-26 16:13 UTC, marcoskichel commented on index.js
> +                const indexFile = join(path, 'index.js');
@ChALkeR Please let me know if this works: https://github.com/ExodusMovement/eslint-plugin-require-extensions/pull/4/commits/6c97becb9dc1774e454d508716817cde2ac93cef

2024-08-26 16:13 UTC, marcoskichel commented on index.js
>              const conflictingFile = join(dirname(path), `${basename(path)}${fileExt}`);
Changed it to `${path}${fileExt}` as suggested

2024-09-01 15:15 UTC, ChALkeR commented on index.js
> +                return possibleExtensions.some((ext) => {
```suggestion
                return [fileExt, ...possibleExtensions].some((ext) => {
```

2024-09-03 09:29 UTC, sparten11740 commented on tests/index.test.js
> -            },
why are we removing these? `../index.js` exists relative to filename, no?

2024-09-03 19:12 UTC, marcoskichel commented on tests/index.test.js
> -            },
Agreed, I introduced a slightly different version of the test on https://github.com/ExodusMovement/eslint-plugin-require-extensions/pull/4/commits/86c7dd255e11623f5fe6b2842fa01a861d60b7b6

The implementation you tagged would be valid because it resolves to the root dir which has a `package.json`, the one I added is in `/examples/dir/nested`, and since `dir/index.js` exists it matches the same criteria as the one you tagged.

2024-09-04 06:26 UTC, sparten11740 commented on tests/index.test.js
> -            },
great, thanks 👍🏼

2024-09-04 06:29 UTC, sparten11740 commented on tests/index.test.js
> +                code: "import plugin from '../'",
can we also add the same test case without the trailing `/` 🙏🏼 ? (`import from '..'`). I am asking because in the original implementation this lead to a bug.

2024-09-04 21:38 UTC, marcoskichel commented on tests/index.test.js
> +                code: "import plugin from '../'",
Ofc we can :)

https://github.com/ExodusMovement/eslint-plugin-require-extensions/pull/4/commits/ddc03f37af37857ef502335c6dec6805997b9e38

2024-09-05 06:54 UTC, sparten11740 commented on tests/index.test.js
> +                code: "import plugin from '../'",
thanks!

2024-09-05 23:57 UTC, marcoskichel commented
Good to go? @ChALkeR

2024-09-06 07:14 UTC, sparten11740 approved these changes
utACK

2024-09-10 15:52 UTC, marcoskichel commented
Ping @ChALkeR

2024-09-10 17:12 UTC, mvayngrib approved these changes

2024-09-10 17:18 UTC, merged